#!/usr/bin/env bash
export PYOVPN_VERSION="2.5.2"
export OPENVPN_AS_BASE="/config"
export OPENVPN_AS_CONFIG="/config/etc/as.conf"
export PATH="/config/scripts:/config/bin:/config/sbin:$PATH"
export LD_LIBRARY_PATH="/config/lib"
export PYTHONHOME="/config"
/config/bin/sqlite3 "$@"
